# Generated by Django 5.1.2 on 2024-11-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='total_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spending',
            name='spent_by',
            field=models.CharField(default='Nivin', max_length=100),
        ),
    ]
