# Generated by Django 5.1.2 on 2024-11-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_spending_quantity_work_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
