# Generated by Django 5.1.2 on 2024-11-08 07:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_employee_aadhar_number_employee_id_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('quantity_allocated', models.PositiveIntegerField()),
                ('date_allocated', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.supplier')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.work')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_number', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spent_by', models.CharField(default='Nivin', max_length=100)),
                ('purchase_bill', models.FileField(blank=True, null=True, upload_to='purchase_bills/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.supplier')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.work')),
            ],
        ),
        migrations.DeleteModel(
            name='Spending',
        ),
    ]
