# Generated by Django 5.1.2 on 2024-11-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_itemallocation_purchase_delete_spending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('working', 'Working'), ('yet_to_start', 'Yet to Start'), ('completed', 'Completed')], max_length=20),
        ),
    ]
